
	/*LTS_SUMAS*--- schema MYDB is removed as not recognizing*/



	CREATE TABLE MYDB.LIS_SUMAS (

	  SUBSCRIBER_ID INT(5) NOT NULL,

	  PRIMARY KEY (SUBSCRIBER_ID));




	ALTER TABLE MYDB.LIS_SUMAS

	ADD COLUMN SUBSCRIBER_NAME VARCHAR(150) NOT NULL AFTER SUBSCRIBER_ID;



	ALTER TABLE MYDB.LIS_SUMAS

	ADD COLUMN SUBSCRIBER_ADDRESS VARCHAR(250) AFTER SUBSCRIBER_NAME;  



	ALTER TABLE MYDB.LIS_SUMAS

	ADD COLUMN CREATED_TIMESTAMP TIMESTAMP NOT NULL AFTER SUBSCRIBER_ADDRESS;



	ALTER TABLE MYDB.LIS_SUMAS

	ADD COLUMN CREATED_BY VARCHAR(50) NOT NULL AFTER CREATED_TIMESTAMP;



	ALTER TABLE MYDB.LIS_SUMAS

	ADD COLUMN UPDATED_TIMESTAMP TIMESTAMP AFTER CREATED_BY;



	ALTER TABLE MYDB.LIS_SUMAS

	ADD COLUMN UPDATED_BY VARCHAR(50) AFTER UPDATED_TIMESTAMP; 



	/*MYDB.LIS_UTMCS*/


	CREATE TABLE MYDB.LIS_UTMCS (

	  USER_TYPE_ID INT(3) NOT NULL,
	  SUBSCRIBER_ID INT(5) NOT NULL,
	  PRIMARY KEY (USER_TYPE_ID)
	);

	ALTER TABLE MYDB.LIS_UTMCS ADD foreign key(SUBSCRIBER_ID)
	 REFERENCES MYDB.LIS_SUMAS(SUBSCRIBER_ID);
		

	ALTER TABLE MYDB.LIS_UTMCS

	ADD COLUMN USER_TYPE_NAME VARCHAR(30) NOT NULL AFTER USER_TYPE_ID; 



	ALTER TABLE MYDB.LIS_UTMCS

	ADD COLUMN CREATED_TIMESTAMP TIMESTAMP NOT NULL AFTER USER_TYPE_NAME;



	ALTER TABLE MYDB.LIS_UTMCS

	ADD COLUMN CREATED_BY VARCHAR(50) NOT NULL AFTER CREATED_TIMESTAMP;



	ALTER TABLE MYDB.LIS_UTMCS

	ADD COLUMN UPDATED_TIMESTAMP TIMESTAMP AFTER CREATED_BY;



	ALTER TABLE MYDB.LIS_UTMCS

	ADD COLUMN UPDATED_BY VARCHAR(50) AFTER UPDATED_TIMESTAMP; 


