
/*LIS_UMACS*/

CREATE TABLE MYDB.LIS_UMACS (

  USER_ID VARCHAR(10) NOT NULL,
  SUBSCRIBER_ID INT(5) NOT NULL,
  PRIMARY KEY (USER_ID),
  FOREIGN KEY (SUBSCRIBER_ID) REFERENCES LIS_SUMAS(SUBSCRIBER_ID)
    );



ALTER TABLE MYDB.LIS_UMACS
ADD COLUMN USER_NAME VARCHAR(20) NOT NULL AFTER SUBSCRIBER_ID;  


ALTER TABLE MYDB.LIS_UMACS
ADD COLUMN OLD_PASSWORD2  VARCHAR(20) NOT NULL AFTER USER_NAME; 



ALTER TABLE MYDB.LIS_UMACS

ADD COLUMN OLD_PASSWORD1  VARCHAR(20) NOT NULL AFTER OLD_PASSWORD2; 



ALTER TABLE MYDB.LIS_UMACS

ADD COLUMN ACTIVE_PASSWORD  VARCHAR(20) NOT NULL AFTER OLD_PASSWORD1; 



ALTER TABLE MYDB.LIS_UMACS

ADD COLUMN CREATED_TIMESTAMP TIMESTAMP NOT NULL AFTER ACTIVE_PASSWORD;



ALTER TABLE MYDB.LIS_UMACS

ADD COLUMN CREATED_BY VARCHAR(50) NOT NULL AFTER CREATED_TIMESTAMP;



ALTER TABLE MYDB.LIS_UMACS

ADD COLUMN UPDATED_TIMESTAMP TIMESTAMP AFTER CREATED_BY;



ALTER TABLE MYDB.LIS_UMACS

ADD COLUMN UPDATED_BY VARCHAR(50) AFTER UPDATED_TIMESTAMP; 


/*LTS_CMDCS*/

CREATE TABLE MYDB.LIS_CMDCS(

  CMDCS_ID INT NOT NULL,
  PRIMARY KEY (CMDCS_ID),
  SUBSCRIBER_ID INT(5) NOT NULL,
  USER_ID VARCHAR(10) NOT NULL,
   FOREIGN KEY (SUBSCRIBER_ID) REFERENCES LIS_SUMAS(SUBSCRIBER_ID),
   FOREIGN KEY (USER_ID) REFERENCES LIS_UMACS(USER_ID));

ALTER TABLE `MYDB`.`LIS_CMDCS` 
CHANGE COLUMN `CMDCS_ID` `CMDCS_ID` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN COMP_PROD_DRAW_NUM VARCHAR(50) NOT NULL AFTER CMDCS_ID; 
  
ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN CUST_NAME_ADDR VARCHAR(250) NOT NULL AFTER COMP_PROD_DRAW_NUM;   
  
  ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN COMP_PROD_NAME VARCHAR(50) NOT NULL AFTER  CUST_NAME_ADDR;   

  ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN COMP_PROD_NUM VARCHAR(50) NOT NULL AFTER  COMP_PROD_NAME; 

  ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN COMP_PROD_MATERIAL VARCHAR(50) NOT NULL AFTER COMP_PROD_NUM ; 



ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN COMP_PROD_MANUFAC_UNITS VARCHAR(5) NOT NULL AFTER COMP_PROD_MATERIAL ; 


ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN COMP_PROD_NOTES VARCHAR(150)  AFTER COMP_PROD_MANUFAC_UNITS ; 


ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN CREATED_TIMESTAMP VARCHAR(50) NOT NULL AFTER COMP_PROD_NOTES;



ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN CREATED_BY VARCHAR(50) NOT NULL AFTER CREATED_TIMESTAMP;



ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN UPDATED_TIMESTAMP TIMESTAMP AFTER CREATED_BY;



ALTER TABLE MYDB.LIS_CMDCS

ADD COLUMN UPDATED_BY VARCHAR(50) AFTER UPDATED_TIMESTAMP; 






 
